version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: sumiked
      POSTGRES_USER: sumiked_user
      POSTGRES_PASSWORD: sumiked_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sumiked_network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://sumiked_user:sumiked_password@postgres:5432/sumiked
      SECRET_KEY: producción-secret-key-cambiar
      SESSION_COOKIE_SECURE: "True"
    depends_on:
      - postgres
    networks:
      - sumiked_network

volumes:
  postgres_data:

networks:
  sumiked_network:
    driver: bridge